const { currentSession } = vi.hoisted(() => ({ currentSession: { user: { id: "", role: "ADMIN", organizationId: "" }, expires: "2099-01-01" } }));
vi.mock("@/lib/auth", () => ({ auth: async () => currentSession }));
import { afterAll, beforeAll, expect, it, vi } from "vitest";
import { withOrganization } from "@/lib/organization-context";
import { systemDatabase } from "@/lib/system-database";
import { prisma } from "@/lib/prisma";
import { previewAutomation } from "@/server/services/automation-preview-service";
import { executeAction } from "@/server/services/automation-service";
import { POST as previewRoute } from "@/app/api/automations/preview/route";
import { POST as createRule } from "@/app/api/automations/route";
import { PATCH as activateRule } from "@/app/api/automations/rules/[id]/route";
const org = `qa-preview-${Date.now()}`;
let conversationId: string, agentId: string, templateId: string, teamId: string;
const scope = (fn: () => Promise<void>) => () => withOrganization(org, fn);
const rule = () => ({ name: "Synthetic preview", trigger: "NEW_INBOUND_MESSAGE" as const, triggerConfig: {}, actionType: "SEND_TEMPLATE" as const, actionConfig: { templateId, variables: { "1": "{name}" } }, isActive: false });
beforeAll(async () => {
  if (new URL(process.env.DATABASE_URL!).searchParams.get("schema") !== "solina_qa_20260923") throw new Error("Isolated QA required");
  await systemDatabase.organization.create({ data: { id: org, name: "Automation preview QA" } });
  currentSession.user.organizationId = org;
  await withOrganization(org, async () => {
    const admin = await prisma.user.create({ data: { name: "Preview admin", email: `${org}@example.test`, passwordHash: "not-a-password", role: "ADMIN" } });
    currentSession.user.id = admin.id;
    teamId = (await prisma.team.create({ data: { name: "Number team" } })).id;
    agentId = (await prisma.user.create({ data: { name: "Other team agent", email: `${org}-agent@example.test`, passwordHash: "not-a-password", role: "AGENT" } })).id;
    const contact = await prisma.contact.create({ data: { name: "QA name", phone: "+972509555555", consentStatus: "OPTED_IN" } });
    conversationId = (await prisma.conversation.create({ data: { contactId: contact.id, source: "MOCK" } })).id;
    templateId = (await prisma.template.create({ data: { name: "preview_test", language: "he", body: "Hello {{1}}", variables: ["1"], status: "APPROVED", category: "MARKETING" } })).id;
  });
});
afterAll(async () => { vi.unstubAllGlobals(); await systemDatabase.$disconnect(); });
it("previews locally without calls, writes, runs, or a marketing reservation; then blocks handoff and opt-out", scope(async () => {
  const fetchSpy = vi.fn(() => { throw new Error("A dry run must not call any provider"); }); vi.stubGlobal("fetch", fetchSpy);
  const before = await prisma.contact.findFirstOrThrow();
  const preview = await previewAutomation(rule(), conversationId);
  expect(preview).toMatchObject({ mode: "DRY_RUN", allowedLocally: true, body: "Hello QA name", provider: "Mock — הדגמה" });
  expect(await prisma.message.count()).toBe(0); expect(await prisma.automationRun.count()).toBe(0); expect(await prisma.auditLog.count()).toBe(0);
  expect((await prisma.contact.findFirstOrThrow()).lastMarketingAt).toEqual(before.lastMarketingAt);
  await prisma.contact.update({ where: { id: before.id }, data: { consentStatus: "OPTED_OUT" } });
  await prisma.conversation.update({ where: { id: conversationId }, data: { assignedAgentId: agentId } });
  const blocked = await previewAutomation(rule(), conversationId);
  expect(blocked.allowedLocally).toBe(false); expect(blocked.reasons.join(" ")).toContain("נציג"); expect(blocked.reasons.join(" ")).toContain("דיוור");
  expect(fetchSpy).not.toHaveBeenCalled(); vi.unstubAllGlobals();
}));
it("rejects inaccessible references and agent API access; creates inactive rules with audit and validates activation", scope(async () => {
  const request = (data: unknown) => new Request("https://qa/api/automations", { method: "POST", body: JSON.stringify(data) });
  expect((await previewRoute(request({ rule: rule(), conversationId: "foreign" }))).status).toBe(400);
  expect((await createRule(request({ ...rule(), actionConfig: { templateId: "foreign" } }))).status).toBe(400);
  currentSession.user.role = "AGENT";
  expect((await previewRoute(request({ rule: rule(), conversationId }))).status).toBe(403);
  currentSession.user.role = "ADMIN";
  const response = await createRule(request(rule())); expect(response.status).toBe(201);
  const saved = (await response.json()).rule; expect(saved.isActive).toBe(false);
  expect(await prisma.auditLog.count({ where: { action: "automation.created", entityId: saved.id } })).toBe(1);
  await prisma.template.update({ where: { id: templateId }, data: { status: "REJECTED" } });
  expect((await activateRule(request({ isActive: true }), { params: Promise.resolve({ id: saved.id }) })).status).toBe(400);
  expect((await activateRule(request({ isActive: true }), { params: Promise.resolve({ id: "foreign" }) })).status).toBe(404);
  expect((await prisma.automationRule.findUniqueOrThrow({ where: { id: saved.id } })).isActive).toBe(false);
}));
it("blocks actual automated assignment across number teams and allows an eligible agent", scope(async () => {
  const sender = await prisma.providerCredential.create({ data: { provider: "mock", teamId, config: {}, isActive: false } });
  await prisma.conversation.update({ where: { id: conversationId }, data: { providerCredentialId: sender.id, assignedAgentId: null } });
  const assign = { ...rule(), actionType: "ASSIGN_AGENT" as const, actionConfig: { agentId } };
  expect((await previewAutomation(assign, conversationId)).allowedLocally).toBe(false);
  expect(await executeAction("ASSIGN_AGENT", { agentId }, { conversationId })).toHaveProperty("skipped");
  expect((await prisma.conversation.findUniqueOrThrow({ where: { id: conversationId } })).assignedAgentId).toBeNull();
  await prisma.user.update({ where: { id: agentId }, data: { teamId } });
  expect((await previewAutomation(assign, conversationId)).allowedLocally).toBe(true);
  expect(await executeAction("ASSIGN_AGENT", { agentId }, { conversationId })).toEqual({ assignedAgentId: agentId });
  expect((await prisma.conversation.findUniqueOrThrow({ where: { id: conversationId } })).assignedAgentId).toBe(agentId);
}));
