/* eslint-disable @typescript-eslint/no-require-imports */
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const baseURL = 'http://localhost:3101';
const artifactDir = '/tmp/solina-qa-browser';
const operationsOnly = process.argv.includes('--operations-only');
fs.mkdirSync(artifactDir, { recursive: true });
(async () => {
  const browser = await chromium.launch({ headless: true });
  const errors = [];
  async function login(user) {
    const context = await browser.newContext({ baseURL, viewport: { width: 1440, height: 1000 } });
    const page = await context.newPage(); page.setDefaultTimeout(90000); page.setDefaultNavigationTimeout(90000);
    page.on('pageerror', (error) => errors.push(error.message));
    await page.goto('/login');
    await page.getByLabel('אימייל').fill(`${user}@example.test`);
    await page.getByLabel('סיסמה', { exact: true }).fill('QA-only-Password-2026!');
    await page.getByRole('button', { name: 'התחברות', exact: true }).click();
    await page.waitForURL('**/inbox');
    return { page, context, request: context.request };
  }
  async function verifyHistory(a) {
    const historyList = (await (await a.request.get('/api/conversations?search=QA%20history%20pagination')).json()).conversations;
    assert.equal(historyList.length, 1);
    await a.page.goto(`/inbox/${historyList[0].id}`);
    await a.page.getByText('QA history 105', { exact: true }).waitFor({ state: 'attached' });
    assert.equal(await a.page.getByText('QA history 000', { exact: true }).count(), 0);
    await a.page.getByRole('button', { name: 'טען הודעות קודמות', exact: true }).scrollIntoViewIfNeeded();
    const anchorBefore = await a.page.getByText('QA history 105', { exact: true }).boundingBox();
    await a.page.getByRole('button', { name: 'טען הודעות קודמות', exact: true }).click();
    await a.page.getByText('QA history 005', { exact: true }).waitFor({ state: 'attached' });
    const anchorAfter = await a.page.getByText('QA history 105', { exact: true }).boundingBox();
    assert.ok(Math.abs(anchorAfter.y - anchorBefore.y) < 60, 'pagination should preserve visible history position');
    await a.page.getByRole('button', { name: 'טען הודעות קודמות', exact: true }).click();
    await a.page.getByText('QA history 000', { exact: true }).waitFor({ state: 'attached' });
    assert.equal(await a.page.getByRole('button', { name: 'טען הודעות קודמות', exact: true }).count(), 0);
    assert.equal(await a.page.locator('p.whitespace-pre-wrap').filter({ hasText: /^QA history/ }).count(), 205);
    console.log('PASS three history pages with 205 equal-timestamp messages; no gaps or duplicates');
  }
  try {
    if (process.argv.includes('--history-only')) { await verifyHistory(await login('qa-agent-a')); assert.deepEqual(errors, []); return; }
    const admin = await login('qa-admin'); console.log('PASS browser login ADMIN');
    const qaSource = `QA WhatsApp ${Date.now()}`;
    const created = await admin.request.post('/api/contacts', { data: { name: 'QA browser lead', phone: '+97250' + String(Date.now()).slice(-7), consentStatus: 'OPTED_IN', tagIds: [] } });
    assert.equal(created.status(), 201);
    const contactId = (await created.json()).contact.id;
    await admin.page.goto(`/contacts/${contactId}`);
    await admin.page.getByRole('button', { name: 'פתח שיחה ושייך לנציג' }).click();
    await admin.page.waitForURL('**/inbox/*');
    const id = admin.page.url().split('/').at(-1);
    await admin.page.getByRole('combobox').nth(1).click();
    await admin.page.getByRole('option', { name: 'qa-agent-a', exact: true }).click();
    await admin.page.getByText('השיוך עודכן', { exact: true }).waitFor();
    console.log('PASS browser start lead conversation and assign representative');
    await admin.page.goto('/templates');
    const a = await login('qa-agent-a');
    await a.page.goto('/templates');
    const b = await login('qa-agent-b');
    await b.page.goto('/templates');
    assert.equal((await b.request.get(`/api/conversations/${id}/messages`)).status(), 404);
    assert.equal((await b.request.get(`/api/contacts/${contactId}`)).status(), 404);
    assert.equal((await b.request.patch(`/api/conversations/${id}/assign`, { data: { agentId: 'qa-agent-b' } })).status(), 404);
    assert.equal((await a.request.post('/api/templates', { data: {} })).status(), 403);
    assert.equal((await a.request.get('/api/campaigns')).status(), 403);
    console.log('PASS authenticated cross-agent access and management restrictions');
    await a.page.goto(`/inbox/${id}`);
    if (!operationsOnly) {
    assert.equal(await a.page.getByPlaceholder('הקלד הודעה...').count(), 0);
    await a.page.getByRole('button', { name: 'שליחת תבנית מאושרת' }).click();
    await a.page.getByRole('combobox', { name: 'תבנית הודעה' }).selectOption('qa-template');
    await a.page.getByRole('textbox', { name: 'משתנה 1', exact: true }).fill('לקוח בדיקה');
    const templateSent = a.page.waitForResponse((r) => r.url().endsWith(`/api/conversations/${id}/messages`) && r.request().method() === 'POST');
    await a.page.getByRole('button', { name: 'שלח', exact: true }).click();
    assert.equal((await templateSent).status(), 200);
    console.log('PASS approved template UI outside service window (mock delivery)');
    assert.equal((await admin.request.post('/api/demo/simulate-inbound', { data: { contactId, body: 'שלום מהלקוח לבדיקת דפדפן', type: 'TEXT' } })).status(), 200);
    await a.page.getByRole('button', { name: 'סגור תבניות' }).click();
    await a.page.getByPlaceholder('הקלד הודעה...').fill('תשובת נציג בבדיקת דפדפן');
    const textSent = a.page.waitForResponse((r) => r.url().endsWith(`/api/conversations/${id}/messages`) && r.request().method() === 'POST');
    await a.page.getByRole('button', { name: 'שלח', exact: true }).click();
    assert.equal((await textSent).status(), 200);
    await a.page.locator('p.whitespace-pre-wrap').filter({ hasText: 'תשובת נציג בבדיקת דפדפן' }).waitFor();
    const draftSaved = a.page.waitForResponse((r) => r.url().endsWith(`/api/conversations/${id}/draft`) && r.request().method() === 'PUT' && r.request().postData()?.includes('טיוטת QA'));
    await a.page.getByPlaceholder('הקלד הודעה...').fill('טיוטת QA לשמירה לאחר רענון');
    assert.equal((await draftSaved).status(), 200);
    await a.page.reload();
    await a.page.getByPlaceholder('הקלד הודעה...').waitFor();
    await a.page.waitForFunction(() => document.querySelector('textarea[placeholder="הקלד הודעה..."]')?.value === 'טיוטת QA לשמירה לאחר רענון');
    assert.equal((await b.request.get(`/api/conversations/${id}/draft`)).status(), 404);
    console.log('PASS private draft survives refresh and rejects another agent');
    }
    assert.equal((await b.request.post(`/api/conversations/${id}/notes`, { data: { body: 'אסור' } })).status(), 404);
    await a.page.getByText(/הערות פנימיות לצוות/).click();
    await a.page.getByRole('textbox', { name: 'הערה פנימית לצוות' }).fill('QA הערה פנימית שאינה נשלחת ללקוח');
    const noteSaved = a.page.waitForResponse((r) => r.url().endsWith(`/api/conversations/${id}/notes`) && r.request().method() === 'POST');
    await a.page.getByRole('button', { name: 'שמור הערה', exact: true }).click();
    assert.equal((await noteSaved).status(), 201);
    await a.page.getByText('QA הערה פנימית שאינה נשלחת ללקוח', { exact: true }).waitFor();
    const messageHistory = await (await a.request.get(`/api/conversations/${id}/messages`)).json();
    assert.equal(messageHistory.messages.some((m) => m.body === 'QA הערה פנימית שאינה נשלחת ללקוח'), false);
    await a.page.getByRole('link', { name: 'כרטיס לקוח והסרה מדיוור' }).click();
    await a.page.getByText('עריכת פרטי לקוח, תגיות ושדות מותאמים', { exact: true }).click();
    await a.page.getByLabel('מקור ליד', { exact: true }).fill(qaSource);
    await a.page.getByRole('button', { name: 'הוסף שדה', exact: true }).click();
    await a.page.getByRole('textbox', { name: 'שם שדה 1', exact: true }).fill('מוצר');
    await a.page.getByRole('textbox', { name: 'ערך שדה 1', exact: true }).fill('QA CRM');
    const detailsSaved = a.page.waitForResponse((r) => r.url().endsWith(`/api/contacts/${contactId}`) && r.request().method() === 'PATCH');
    await a.page.getByRole('button', { name: 'שמור פרטי לקוח', exact: true }).click();
    assert.equal((await detailsSaved).status(), 200);
    const updatedContact = (await (await a.request.get(`/api/contacts/${contactId}`)).json()).contact;
    assert.equal(updatedContact.source, qaSource);
    assert.equal(updatedContact.customFields[0].value, 'QA CRM');
    assert.equal(updatedContact.notes.some((n) => n.body === 'QA הערה פנימית שאינה נשלחת ללקוח'), true);
    assert.equal((await a.request.get('/api/contacts/export')).status(), 403);
    const exported = await admin.request.get('/api/contacts/export?search=QA%20browser%20lead');
    assert.equal(exported.status(), 200); assert.ok((await exported.text()).includes('QA browser lead'));
    assert.equal((await a.request.post('/api/automations/stop')).status(), 403);
    await a.page.screenshot({ path: `${artifactDir}/crm-editor.png`, fullPage: true, animations: 'disabled' });
    console.log('PASS internal notes and CRM edit persist, stay out of messages, enforce agent/export permissions');
    await verifyHistory(a);


    await a.page.screenshot({ path: `${artifactDir}/inbox-desktop.png`, fullPage: true, animations: "disabled" });
    if (!operationsOnly) {
    console.log('PASS inbound polling enables service reply and outbound message renders');
    await admin.page.goto('/templates');
    await admin.page.getByRole('button', { name: 'תבנית חדשה לאישור' }).click();
    await admin.page.getByRole('textbox', { name: 'שם התבנית', exact: true }).fill('browser_template');
    await admin.page.getByRole('textbox', { name: 'תוכן התבנית', exact: true }).fill('שלום {{1}}, תודה שפנית אלינו.');
    await admin.page.getByRole('textbox', { name: 'דוגמה למשתנה 1', exact: true }).fill('ישראל');
    await admin.page.screenshot({ path: `${artifactDir}/template-submission.png`, fullPage: true, animations: "disabled" });
    const submission = admin.page.waitForResponse((r) => r.url().endsWith('/api/templates') && r.request().method() === 'POST');
    await admin.page.getByRole('button', { name: 'הגש לאישור Meta' }).click();
    assert.equal((await submission).status(), 502);
    await admin.page.getByText('יש לחבר חשבון Meta ולהגדיר Business Account ID לפני הגשה', { exact: true }).waitFor();
    console.log('PASS template submission form with examples; mock mode cannot submit to Meta');
    }
    const listResponse = await admin.request.post('/api/distribution-lists', { data: { name: 'QA browser list', contactIds: [contactId, 'qa-contact-1'] } });
    assert.equal(listResponse.status(), 201);
    const listId = (await listResponse.json()).list.id;
    const campaignName = `QA review campaign ${Date.now()}`;
    const campaignResponse = await admin.request.post('/api/campaigns', { data: { name: campaignName, listId, templateId: 'qa-template', variables: { '1': '{name}' } } });
    assert.equal(campaignResponse.status(), 201);
    const draftCampaign = (await campaignResponse.json()).campaign;
    const review = await admin.request.get(`/api/campaigns/${draftCampaign.id}?preflight=1`);
    assert.equal(review.status(), 200); const reviewData = await review.json();
    assert.equal(reviewData.totalQueued, 2); assert.equal(reviewData.eligible, 1);
    await admin.page.goto('/campaigns');
    await admin.page.locator('article').filter({ has: admin.page.getByRole('heading', { name: campaignName, exact: true }) }).getByRole('button', { name: 'התחל שליחה', exact: true }).click();
    await admin.page.getByRole('region', { name: 'סיכום לפני שליחה' }).waitFor();
    assert.equal(await admin.page.getByRole('button', { name: 'אשר והפעל' }).isEnabled(), true);
    await admin.page.screenshot({ path: `${artifactDir}/campaign-preflight.png`, fullPage: true, animations: 'disabled' });
    await admin.page.getByRole('button', { name: 'סגור סיכום' }).click();
    console.log('PASS campaign preflight UI with real eligibility/exclusion counts (not activated)');
    const duplicated = await admin.request.post(`/api/campaigns/${draftCampaign.id}/duplicate`);
    assert.equal(duplicated.status(), 201);
    const copy = (await duplicated.json()).campaign;
    assert.equal(copy.status, 'DRAFT'); assert.equal(copy.scheduledAt, null); assert.notEqual(copy.id, draftCampaign.id);
    assert.equal((await a.request.post(`/api/campaigns/${draftCampaign.id}/duplicate`)).status(), 403);
    const rule = await admin.request.post('/api/automations', { data: { name: 'QA stop rule', trigger: 'NO_REPLY_TIMEOUT', triggerConfig: { minutes: 30 }, actionType: 'ADD_INTERNAL_NOTE', actionConfig: { body: 'QA only' }, isActive: true } });
    assert.equal(rule.status(), 201);
    const stopped = await admin.request.post('/api/automations/stop');
    assert.equal(stopped.status(), 200); assert.ok((await stopped.json()).stoppedRules >= 1);
    console.log('PASS campaign duplication remains draft; manager stop-all disables rules');
    if (operationsOnly) { assert.deepEqual(errors, []); console.log('PASS operational browser checks complete'); return; }

    await admin.page.getByRole('button', { name: /רשימות תפוצה \(/ }).click();
    await admin.page.getByLabel('שם הרשימה המיובאת').fill('QA mapped import');
    await admin.page.getByLabel('קובץ אנשי קשר CSV').setInputFiles({ name: 'qa.csv', mimeType: 'text/csv', buffer: Buffer.from('customer,mobile,permission\nQA mapped,+972509999900,UNKNOWN\nBad,wrong,UNKNOWN') });
    await admin.page.getByLabel('עמודת name', { exact: true }).selectOption('customer');
    await admin.page.getByLabel('עמודת phone', { exact: true }).selectOption('mobile');
    await admin.page.getByLabel('עמודת consentStatus', { exact: true }).selectOption('permission');
    await admin.page.getByRole('button', { name: 'בדוק והצג תצוגה מקדימה' }).click();
    await admin.page.getByText(/1 ייחודיים תקינים, 0 כפולים, 1 שגיאות/).waitFor();
    assert.equal(await admin.page.getByRole('button', { name: 'ייבא רשימה', exact: true }).isDisabled(), true);
    await admin.page.screenshot({ path: `${artifactDir}/csv-preview.png`, fullPage: true, animations: 'disabled' });
    console.log('PASS CSV column mapping, invalid-row report and disabled commit');
    await admin.page.getByRole('button', { name: 'קמפיינים', exact: true }).click();
    await admin.page.getByText('QA campaign', { exact: true }).waitFor();
    await admin.page.screenshot({ path: `${artifactDir}/campaigns-desktop.png`, fullPage: true, animations: "disabled" });
    await admin.page.setViewportSize({ width: 390, height: 844 });
    await admin.page.screenshot({ path: `${artifactDir}/campaigns-mobile.png`, fullPage: true, animations: "disabled" });
    assert.equal(await admin.page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
    console.log('PASS campaigns render on desktop and mobile without page overflow');
    await admin.page.goto('/settings/whatsapp');
    assert.equal((await admin.request.post('/api/settings/whatsapp/check')).status(), 409);
    await admin.page.screenshot({ path: `${artifactDir}/meta-settings-mobile.png`, fullPage: true, animations: "disabled" });
    await admin.page.setViewportSize({ width: 1440, height: 1000 });
    await admin.page.goto('/settings/users');
    assert.equal((await admin.request.patch('/api/settings/users/qa-agent-b', { data: { password: 'QA-replaced-password-2026!' } })).status(), 200);
    const revoked = await b.request.get('/api/auth/session');
    assert.ok(!(await revoked.json())?.user);
    assert.equal((await admin.request.patch('/api/settings/users/qa-agent-b', { data: { password: 'QA-only-Password-2026!' } })).status(), 200);
    console.log('PASS password reset revokes existing sessions');
    const teamName = `QA team ${Date.now()}`;
    await admin.page.getByLabel('שם צוות חדש').fill(teamName);
    const teamCreated = admin.page.waitForResponse((res) => res.url().endsWith('/api/settings/teams') && res.request().method() === 'POST');
    await admin.page.getByRole('button', { name: 'צור צוות', exact: true }).click();
    const teamResponse = await teamCreated; assert.equal(teamResponse.status(), 201);
    const teamId = (await teamResponse.json()).team.id;
    await admin.page.getByLabel('צוות של qa-agent-b').selectOption(teamId);
    await admin.page.getByText('הצוות עודכן; המשתמש יידרש להיכנס מחדש', { exact: true }).waitFor();
    assert.equal((await a.request.post('/api/settings/teams', { data: { name: 'Forbidden' } })).status(), 403);
    assert.equal((await a.request.patch('/api/settings/users/qa-agent-b', { data: { teamId } })).status(), 403);
    await admin.page.goto('/settings/whatsapp');
    await admin.page.getByRole('region', { name: 'מספרי WhatsApp בעסק' }).waitFor();
    await admin.page.screenshot({ path: `${artifactDir}/multiple-number-settings.png`, fullPage: true, animations: 'disabled' });
    console.log('PASS team creation and membership UI, agent denials, number management view');
    await admin.page.goto('/campaigns');
    await admin.page.getByRole('button', { name: /רשימות תפוצה \(/ }).click();
    const audienceName = `QA saved audience ${Date.now()}`;
    await admin.page.getByLabel('שם רשימת תפוצה', { exact: true }).fill(audienceName);
    await admin.page.getByLabel('קהל שמור לפי תנאים', { exact: true }).check();
    await admin.page.getByRole('button', { name: 'הוסף קבוצת משנה 1', exact: true }).click();
    await admin.page.getByLabel('חיבור תנאים 1.2', { exact: true }).selectOption('OR');
    await admin.page.getByLabel('סוג תנאי 1.2.1', { exact: true }).selectOption('source');
    await admin.page.getByLabel('ערך תנאי 1.2.1', { exact: true }).fill(qaSource);
    await admin.page.getByRole('button', { name: 'הוסף תנאי לקבוצה 1.2', exact: true }).click();
    await admin.page.getByLabel('סוג תנאי 1.2.2', { exact: true }).selectOption('source');
    await admin.page.getByLabel('ערך תנאי 1.2.2', { exact: true }).fill('QA nonexistent source');
    await admin.page.getByRole('button', { name: 'בדוק קהל וזכאות', exact: true }).click();
    await admin.page.getByText(/1 מתאימים לתנאים; 0 הוחרגו; 1 זכאים/).waitFor();
    await admin.page.screenshot({ path: `${artifactDir}/saved-audience-editor.png`, fullPage: true, animations: 'disabled' });
    const savedAudienceResponse = admin.page.waitForResponse((res) => res.url().endsWith('/api/distribution-lists') && res.request().method() === 'POST');
    await admin.page.getByRole('button', { name: 'שמור רשימה', exact: true }).click();
    const savedAudience = await savedAudienceResponse; assert.equal(savedAudience.status(), 201);
    const savedAudienceId = (await savedAudience.json()).list.id;
    await admin.page.getByRole('button', { name: 'קמפיינים', exact: true }).click();
    await admin.page.getByLabel('רשימת תפוצה לקמפיין', { exact: true }).selectOption(savedAudienceId);
    await admin.page.getByLabel('קהלים להחרגה', { exact: true }).selectOption(listId);
    await admin.page.getByRole('button', { name: 'בדוק קהל וזכאות', exact: true }).click();
    await admin.page.getByText(/1 מתאימים לתנאים; 1 הוחרגו; 0 זכאים/).waitFor();
    assert.equal((await a.request.post('/api/distribution-lists/preview', { data: { listId: savedAudienceId } })).status(), 403);
    await admin.page.setViewportSize({ width: 390, height: 844 });
    assert.equal(await admin.page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
    await admin.page.screenshot({ path: `${artifactDir}/audience-exclusions-mobile.png`, fullPage: true, animations: 'disabled' });
    console.log('PASS saved AND/OR audience editor, live counts, persistence, campaign exclusions, agent denial and mobile');

    assert.deepEqual(errors, []);
    console.log('PASS no browser runtime errors; screenshots saved to ' + artifactDir);
  } catch (error) {
    for (const [i, context] of browser.contexts().entries()) {
      for (const [j, page] of context.pages().entries()) await page.screenshot({ path: `${artifactDir}/failure-${i}-${j}.png`, fullPage: true, animations: "disabled" }).catch(() => {});
    }
    throw error;
  } finally { await browser.close(); }
})().catch((error) => { console.error(error.name, error.message.split("Call log:")[0]); process.exitCode = 1; });
